### ISSUE TITLE
Deployment with GCP

### ISSUE THREAD

**Issue by great-park** [KUGODS-Wonder/Wonder-Backend#8]
GCP을 이용하여 배포를 진행한다.

- [x] GCP 인스턴스 생성
- [x] spring project 배포
- [x] localhost -> public IP address 교체
- [x] nginx - reverse proxy
- [x] Docker 사용
- [x] 도메인 연결(for 구글 로그인)
- [x] https 적용(for 구글 로그인)

**Comment by great-park** [comment]
구글 소셜 로그인 정책상 (1) https 통신 (2) 도메인 연결 등을 만족시켜야 한다. 따라서 아래와 같이 수정한다.


1. ./docker-compose,yml
```yml
version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - spring
  spring:
    container_name: spring-app
    image: "cksgh1735/spring2:latest"
    ports:
      - 8080:8080

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot

```
2. ./nginx/conf.d/app.conf
```
server {
    listen 80;
    server_name ku-wonder.shop www.ku-wonder.shop;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ku-wonder.shop www.ku-wonder.shop
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/ku-wonder.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ku-wonder.shop/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://spring:8080;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }
}
```
